### PR TITLE
book skeleton

### LINKED ISSUE #15: Small style edits
- [x] Add GitHub icon to navbar that links back here
- [x] Add a default fill color. Could be any of the colors that look good in the `--highligh-*` vars in the CSS
- [x] @brendanhcullen tries to add sidenotes

The first two are simple, the third seems much more difficult. But, I also wanted to mention that if you're able to get this to work we should move the page navigation to be at the bottom always. Right now, page navigation is on the sides of the text if the window is wide enough, and at the bottom otherwise. If we can build in side-notes, we should probably just have it at the bottom always.

### LINKED ISSUE #24: Book splitting
There's a number of different options for how to split the book. Currently the table of contents shows too many levels of headers by default. I think there's a way we can change that. I'd like it just to show the chapter level unless you're on that chapter. I think that's possible but not sure. This is mostly a note to myself to come back to this later.

### PR DESCRIPTION
**Pull request by brendanhcullen**
This PR creates a skeleton for the book with (for now) mostly empty chapters. The book is split into 4 sections, each with ~8-10 chapters: 
- Foundations
- Data visualization and communication
- Functional programming
- Machine learning

The book also contains Preface and Welcome sections at the very top (which could perhaps ultimately be collapsed into one section). Eventually it might be nice to have a logo to place at the very top and perhaps link to open-source license, etc. (à la https://stat545.com/).

This PR also makes the following updates to `_output.yaml`:
- allows for continuous scrolling between sections within a chapter since that allows for easier navigation for the reader (particularly when a chapter includes very short sections), and the current section in highlighted in the table of contents. (Of course, feel free to revert this if you don't like it). 
- adds Github icon to navbar (closes #15) and limits sharing options to Github and Twitter (since most of the others seem extraneous)
- adds "edit on Github" and "download" buttons to navbar

I've added a `bookdown.yml` file that contains all of the chapter names in the desired order in a YAML filed called `rmd_files`. I opted for this approach rather than prefixing all of the chapter names with a number (e.g. `01_introduction-to-R.Rmd`) because this allows for automatic number of chapters, and if we decide to add or remove a chapter this will allow us to avoid having to manually re-number all of the chapters.

### CODE REVIEW

**Comment by datalorax** [comment]
Wonderful! The only thing I'm not sure of is the continuous scrolling. For chapters like the feature engineering one it gets really long. But maybe that's better? I'm not sure. We can go with this for now and see how we like it, and we can always revert later if we decide we don't.

I like the idea of using `_output.yaml` too and was also thinking we should go that way. The only thing is we might want to re-name the existing files so they don't have the numbers because that could be confusing if they don't match. Then again, it also could be confusing if the order in your local directory is really different than the chapter order (i.e., if they're sorted in alphabetical order). But I guess for now I'd suggest we just remove the numbers from the file names.

Any other thoughts before we merge this in @ohmaddi?

**Comment by brendanhcullen** [comment]
@datalorax great points!

For posterity, if we want to undo continuous scrolling at any point, we'll just need to change `split_by: chapter` to `split_by: section` in `_output.yml`.

re: file naming, I actually re-named the existing chapter files in 43f8683 (sorry for the bloated commit). Perhaps once we feel really confident that the number of chapters & chapter order won't change we can re-name the files with their number?In the meantime, I figured that few people will be interacting with the repo besides us, but if we wanted a clearer indication of chapter order in the repo, I'm more than happy to add the ordered list in the README.

**Comment by datalorax** [comment]
Sounds great! Thanks for all your help on this. I think we can go ahead and merge this in, but I'll wait a bit longer to see if Ouafaa has any feedback first.

**Comment by ohmaddi** [comment]
@brendanhcullen thank you so much for this. It all looks great to me. For the split, by section might be better but this might be the effect of what we go used to so let’s try the continuous scrolling and see how it feels. For the skeleton, do we want to add a chapter on cloud computing in the machine learning section? 

I plan to start working on this chapter soon mostly with GC.

**Comment by datalorax** [comment]
Good catch @ohmaddi! Yes, I think we should do that. Would this be maybe the fourth chapter in the ML section? Also, would you mind updating the book outline in the [project](https://github.com/datalorax/sds-r/projects/1) with this change?

**Comment by ohmaddi** [comment]
Great - @datalorax I just changed it in the project menu. I added it as a 4th chapter. Another option could be the last chapter so they can actually try running models as they set up cloud accounts. It’s a conundrum but I could see it beneficial as either 4th or last.

**Comment by brendanhcullen** [comment]
@datalorax @ohmaddi thanks, y'all -- I added Cloud computing as the 4th chapter in the ML section for now (1f268cc).

**Comment by datalorax** [comment]
Perfect! I'll merge it in now. Thank you both!

**Pull request merged**
