### PR TITLE
investigate tibble printing issue

### PR DESCRIPTION
**Pull request by brendanhcullen**

### CODE REVIEW

**Comment by datalorax** [comment]
Preview is here

https://5f91dbc80cd3a900fde58ca8--nervous-golick-ef3308.netlify.app

I don't know why that link above doesn't work and I don't know how to fix it, but I can get the preview deploy through the logs.

**Comment by brendanhcullen** [comment]
Yeah I'm sort of at a loss as to why the PR deploy previews aren't working. I tried to view the deploy preview link from the logs on Netlfiy and that link isn't working for me either: 

https://5f91da1211562d00074e6cd0--nervous-golick-ef3308.netlify.app/ ("page not found" error). 

I'm looking into this more right now. I came across [this blog post](https://www.hvitfeldt.me/blog/bookdown-netlify-github-actions/) by Emil Hvitfeldt, which seems to be the most up-to-date advice on deploying bookdown sites with Netlify and continuous deployment with Github Actions. From what I can tell, though it looks like all of these boxes have been checked. The only thing I can think of that might warrant a closer look is the "NETLIFY_AUTH_TOKEN" and "NETLIFY_SITE_ID" as Github "Secrets".

**Comment by datalorax** [comment]
Ha! That's the blog post I used to set this up! I actually reached out to him through a twitter DM and he said he's not sure how to fix it either.

Does the link I posted work? Yours does not for me, but the one I posted does. I think it's up to date?

**Comment by brendanhcullen** [comment]
Haha of course 😆. Dang. Just for troubleshooting purposes I'll try forking the repo and deploying my fork to netlify to see if I am getting the same issue with deploy previews.

**Comment by brendanhcullen** [comment]
For posterity, the solution to our issue was to set `Publish directory` to `_book` on Netlify under **Site Settings > Build & deploy > Build Settings**, which fixed both deploy previews and tibble printing.

**Pull request closed without merging**
